// AUTO-GENERATED by sdui. You can freely add your own exports below.
// Do NOT remove the `// sdui:end` comment — the CLI uses it to append entries.

import 'package:sdui_library/sdui_library.dart';

// ── Encoders (DSL — pure Dart) ────────────────────────────────────────────────
export 'rating_stars/rating_stars_encoder.dart';
export 'my_widget/my_widget_encoder.dart';
export 'my_badge/my_badge_encoder.dart';

// ── Builders (runtime — Flutter) ──────────────────────────────────────────────
import 'rating_stars/rating_stars_builder.dart';
import 'my_widget/my_widget_builder.dart';
import 'my_badge/my_badge_builder.dart';

/// Registers all custom SDUI widgets with [SduiParser].
///
/// Call this **once** at app startup, before any JSON is parsed:
///
/// ```dart
/// import 'package:example/sdui_widgets/sdui_custom_widgets.dart';
///
/// void main() {
///   registerCustomWidgets();
///   runApp(MyApp());
/// }
/// ```
void registerCustomWidgets() {
  SduiParser.registerWidget('RatingStars', RatingStarsBuilder.fromJson);
  SduiParser.registerWidget('MyWidget', MyWidgetBuilder.fromJson);
  SduiParser.registerWidget('MyBadge', MyBadgeBuilder.fromJson);
  // sdui:end — do not remove this line
}
