// AUTO-GENERATED by: dart run sdui add-widget MyWidget
// Edit freely — this file is yours.
//
// This file is the runtime renderer for [MyWidget].
// It reads the JSON produced by the DSL encoder and returns a Flutter widget.

import 'package:flutter/material.dart';

/// Builds a [MyWidget] Flutter widget from an SDUI JSON definition.
///
/// ### Expected JSON shape
/// ```json
/// {
///   "widget": "MyWidget",
///   "properties": {
///     "label": "Hello!"
///   }
/// }
/// ```
class MyWidgetBuilder {
  MyWidgetBuilder._();

  static Widget fromJson(Map<String, dynamic> json) {
    final props = (json['properties'] as Map<String, dynamic>?) ?? {};
    final label = (props['label'] as String?) ?? '';

    // TODO: Replace with your real [MyWidget] implementation.
    if (label.isEmpty) {
      return Text(
        '[MyWidget] — no content provided',
        style: const TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
      );
    }

    return Text(label);
  }
}
