// AUTO-GENERATED by: dart run sdui add-widget MyWidget
// Edit freely — this file is yours.
//
// IMPORTANT: Keep this file Flutter-free (no `package:flutter` imports).
// The CLI runs it in a plain Dart VM to serialize your widget to JSON.

import 'package:sdui_library/sdui_dsl.dart';

/// DSL encoder for [MyWidget].
///
/// Use this in your DSL definition files to compose [MyWidget] nodes
/// and export them to JSON via the SDUI CLI.
///
/// ### Example
/// ```dart
/// import 'package:sdui_library/sdui_dsl.dart';
/// import 'sdui_widgets/my_widget/my_widget_encoder.dart';
///
/// final _ = MyWidget(
///   key: Key('my_my_widget'),
///   label: 'Hello!',
/// );
/// ```
///
/// Then export:
/// ```bash
/// dart run sdui export <file_name> my_my_widget
/// ```
class MyWidget extends SduiNode {
  // TODO: Replace with your real widget properties.
  final String label;

  MyWidget({Key? key, required this.label}) : super(key: key);

  @override
  Map<String, dynamic> toJson() => {
    'widget': 'MyWidget',
    'properties': {
      'label': label, // TODO: Add more properties here.
    },
  };
}
