// AUTO-GENERATED by: dart run sdui add-widget ProfileCard
// Edit freely — this file is yours.
//
// IMPORTANT: Keep this file Flutter-free (no `package:flutter` imports).
// The CLI runs it in a plain Dart VM to serialize your widget to JSON.

import 'package:sdui_library/sdui_dsl.dart';

/// DSL encoder for [ProfileCard].
///
/// Use this in your DSL definition files to compose [ProfileCard] nodes
/// and export them to JSON via the SDUI CLI.
///
/// ### Example
/// ```dart
/// import 'package:sdui_library/sdui_dsl.dart';
/// import 'sdui_widgets/profile_card/profile_card_encoder.dart';
///
/// final _ = ProfileCard(
///   key: Key('my_profile_card'),
///   label: 'Hello!',
/// );
/// ```
///
/// Then export:
/// ```bash
/// dart run sdui export <file_name> my_profile_card
/// ```
class ProfileCard extends SduiNode {
  // TODO: Replace with your real widget properties.
  final String label;

  ProfileCard({
    Key? key,
    required this.label,
  }) : super(key: key);

  @override
  Map<String, dynamic> toJson() => {
        'widget': 'ProfileCard',
        'properties': {
          'label': label, // TODO: Add more properties here.
        },
      };
}
