// Generated by: dart run sdui add-widget RatingStars
// Then filled in with a real implementation.
//
// This file is the runtime renderer for [RatingStars].
// It reads the JSON produced by the DSL encoder and returns a Flutter widget.

import 'package:flutter/material.dart';

/// Builds a [RatingStars] Flutter widget from an SDUI JSON definition.
///
/// ### Expected JSON shape
/// ```json
/// {
///   "widget": "RatingStars",
///   "properties": {
///     "rating": 4.5,
///     "maxStars": 5,
///     "label": "4.5 out of 5",
///     "starColor": "#F59E0B",
///     "inactiveStarColor": "#E5E7EB",
///     "size": 24.0
///   }
/// }
/// ```
class RatingStarsBuilder {
  RatingStarsBuilder._();

  static Widget fromJson(Map<String, dynamic> json) {
    final props = (json['properties'] as Map<String, dynamic>?) ?? {};

    final rating = (props['rating'] as num?)?.toDouble() ?? 0.0;
    final maxStars = (props['maxStars'] as int?) ?? 5;
    final label = props['label'] as String?;
    final size = (props['size'] as num?)?.toDouble() ?? 22.0;

    final starColor =
        _hexToColor(props['starColor'] as String?) ?? const Color(0xFFF59E0B);
    final inactiveColor =
        _hexToColor(props['inactiveStarColor'] as String?) ??
        const Color(0xFFE5E7EB);

    if (rating < 0) {
      return const Text(
        '[RatingStars] — no content provided',
        style: TextStyle(color: Colors.grey, fontStyle: FontStyle.italic),
      );
    }

    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        // Stars
        Row(
          mainAxisSize: MainAxisSize.min,
          children: List.generate(maxStars, (index) {
            final filled = index < rating.floor();
            final half = !filled && index < rating;
            return Icon(
              filled
                  ? Icons.star_rounded
                  : half
                  ? Icons.star_half_rounded
                  : Icons.star_outline_rounded,
              color: (filled || half) ? starColor : inactiveColor,
              size: size,
            );
          }),
        ),
        // Optional label
        if (label != null && label.isNotEmpty) ...[
          const SizedBox(width: 6),
          Text(
            label,
            style: TextStyle(
              fontSize: size * 0.6,
              fontWeight: FontWeight.w600,
              color: const Color(0xFF6B7280),
            ),
          ),
        ],
      ],
    );
  }

  static Color? _hexToColor(String? hex) {
    if (hex == null) return null;
    final clean = hex.replaceAll('#', '');
    if (clean.length == 6) {
      return Color(int.parse('FF$clean', radix: 16));
    }
    if (clean.length == 8) {
      return Color(int.parse(clean, radix: 16));
    }
    return null;
  }
}
