// Generated by: dart run sdui add-widget RatingStars
// Then filled in with a real implementation.
//
// IMPORTANT: Keep this file Flutter-free (no `package:flutter` imports).
// The CLI runs it in a plain Dart VM to serialize your widget to JSON.

import 'package:sdui_library/sdui_dsl.dart';

/// DSL encoder for [RatingStars].
///
/// Encodes a star-rating display widget into SDUI JSON.
///
/// ### Example
/// ```dart
/// import 'package:sdui_library/sdui_dsl.dart';
/// import 'sdui_widgets/rating_stars/rating_stars_encoder.dart';
///
/// final _ = RatingStars(
///   key: Key('product_rating'),
///   rating: 4.5,
///   maxStars: 5,
///   label: '4.5 out of 5',
///   starColor: '#F59E0B',
///   size: 24.0,
/// );
/// ```
///
/// Then export:
/// ```bash
/// dart run sdui export <file_name> product_rating
/// ```
class RatingStars extends SduiNode {
  final double rating;
  final int maxStars;
  final String? label;
  final String? starColor;
  final String? inactiveStarColor;
  final double? size;

  RatingStars({
    super.key,
    required this.rating,
    this.maxStars = 5,
    this.label,
    this.starColor,
    this.inactiveStarColor,
    this.size,
  });

  @override
  Map<String, dynamic> toJson() => {
        'widget': 'RatingStars',
        'properties': {
          'rating': rating,
          'maxStars': maxStars,
          if (label != null) 'label': label,
          if (starColor != null) 'starColor': starColor,
          if (inactiveStarColor != null) 'inactiveStarColor': inactiveStarColor,
          if (size != null) 'size': size,
        },
      };
}
