// AUTO-GENERATED by: dart run sdui add-widget RatingStars
// Edit freely — this file is yours.
//
// IMPORTANT: Keep this file Flutter-free (no `package:flutter` imports).
// The CLI runs it in a plain Dart VM to serialize your widget to JSON.

import 'package:sdui_library/sdui_dsl.dart';

/// DSL encoder for [RatingStars].
///
/// Use this in your DSL definition files to compose [RatingStars] nodes
/// and export them to JSON via the SDUI CLI.
///
/// ### Example
/// ```dart
/// import 'package:sdui_library/sdui_dsl.dart';
/// import 'sdui_widgets/rating_stars/rating_stars_encoder.dart';
///
/// final _ = RatingStars(
///   key: Key('my_rating_stars'),
///   label: 'Hello!',
/// );
/// ```
///
/// Then export:
/// ```bash
/// dart run sdui export <file_name> my_rating_stars
/// ```
class RatingStars extends SduiNode {
  // TODO: Replace with your real widget properties.
  final String label;

  RatingStars({
    Key? key,
    required this.label,
  }) : super(key: key);

  @override
  Map<String, dynamic> toJson() => {
        'widget': 'RatingStars',
        'properties': {
          'label': label, // TODO: Add more properties here.
        },
      };
}
