// AUTO-GENERATED by: dart run sdui add-widget RatingStars
// Edit freely — this file is yours.
//
// This file is the runtime renderer for [RatingStars].
// It reads the JSON produced by the DSL encoder and returns a Flutter widget.

import 'package:flutter/material.dart';

/// Builds a [RatingStars] Flutter widget from an SDUI JSON definition.
///
/// ### Expected JSON shape
/// ```json
/// {
///   "widget": "RatingStars",
///   "properties": {
///     "label": "Hello!"
///   }
/// }
/// ```
class RatingStarsBuilder {
  RatingStarsBuilder._();

  static Widget fromJson(Map<String, dynamic> json) {
    final props = (json['properties'] as Map<String, dynamic>?) ?? {};
    final label = (props['label'] as String?) ?? '';

    // TODO: Replace with your real [RatingStars] implementation.
    if (label.isEmpty) {
      return Text(
        '[RatingStars] — no content provided',
        style: const TextStyle(
          color: Colors.grey,
          fontStyle: FontStyle.italic,
        ),
      );
    }

    return Text(label);
  }
}
